name: 'Clean Name'
description: 'Clean a string into a valid artifact name.'
inputs:
  dirty:
    description: 'The string to clean'
    required: true
outputs:
  clean:
    description: 'The cleaned name'
runs:
  using: 'node12'
  main: 'index.js'
